name: 'Configure Datadog Test Visibility'
description: 'Installs Datadog tracers for configured languages and enables Test Visibility'
runs:
  using: "composite"
  steps:
    - name: Run Test Visibility install script
      run: install_script_civisibility.sh >> "$GITHUB_ENV"
      shell: bash
