name: 'Configure Datadog Test Visibility'
description: 'Installs Datadog tracers for configured languages and enables Test Visibility'
inputs:
  languages:
    description: 'List of languages to be instrumented. Can be either all or a space-separated subset of java, js, python, dotnet'
    required: true
  service-name:
    description: 'The name of the service or library being tested. This value is used for populating "test.service" tag in Datadog.'
    required: true
  api-key:
    description: 'Datadog API key. Can be found at https://app.datadoghq.com/organization-settings/api-keys'
    required: true
outputs:
  node-options:
    description: "NODE_OPTIONS environment variable value"
    value: ${{ steps.run-configuration-script.outputs.node-options }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run configuration script
      id: run-configuration-script
      run: |
        install_script_civisibility.sh >> "$GITHUB_ENV"

        # Setting NODE_OPTIONS via GITHUB_ENV is not allowed
        echo "node-options=$NODE_OPTIONS -r $DD_TRACER_FOLDER/lib/node_modules/dd-trace/ci/init" >> $GITHUB_OUTPUT

        echo $DD_TRACER_FOLDER
        ls -la $DD_TRACER_FOLDER
      shell: bash
      env:
        DD_CIVISIBILITY_INSTRUMENTATION_LANGUAGES: ${{ inputs.languages }}
        DD_TRACER_FOLDER: ${{ github.workspace }}/.datadog

    - name: Propagate service name and API key from inputs to environment variables
      run: |
        echo "DD_SERVICE=${{ inputs.service-name }}" >> "$GITHUB_ENV"
        echo "DD_API_KEY=${{ inputs.api-key }}" >> "$GITHUB_ENV"
      shell: bash
